# Lines configured by zsh-newuser-install
HISTSIZE=1000
SAVEHIST=50000
setopt HIST_IGNORE_ALL_DUPS
HISTFILE=~/.zsh_history
setopt incappendhistory sharehistory extendedhistory histexpiredupsfirst histignorespace
setopt autocd nomatch notify
unsetopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install

bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
bindkey "\e[3;5~" delete-word
bindkey "^_" describe-key-briefly # C-?

autoload edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# http://superuser.com/q/613685/58037
#ZLE_REMOVE_SUFFIX_CHARS=" ;"
#ZLE_SPACE_SUFFIX_CHARS="&|"

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' format '-- completing %d --'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' preserve-prefix '//[^/]##/'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.oh-my-zsh-tweaks"
ZSH_THEME=wedisagree
HYPHEN_INSENSITIVE=true
COMPLETION_WAITING_DOTS=true
DISABLE_UNTRACKED_FILES_DIRTY=true
DISABLE_AUTO_TITLE=true
HIST_STAMPS="yyyy-mm-dd"
plugins=(git branch command-not-found docker web-search cabal npm pip virtualbox)
source $ZSH/oh-my-zsh.sh

local -H TITLE

REPORTTIME=3 # output time statistics when command is running longer than 3 sec

set_title() {
	case $TERM in
	xterm*|rxvt*)
		print -n "\e]0;$@\a"
		;;
	*)
		;;
	esac
}

userhost() {
	if [[ -n $SSH_CLIENT ]]
	then print -P "[%n@%m]"
	else print -P "%n"
	fi
}

check_stat() {
	local stop=$((`date "+%s + %N / 1.0e9"`))
	let local "elapsed = ${stop} - ${cmd_start_time}"
	(( $elapsed > 15.0 )) && [ "${cmd_abbrev}" != "" ] && \
	    notify-send -i guake "Done running:" "${cmd_abbrev}\n$(LC_ALL=C printf '%.2f' ${elapsed})s"
	cmd_abbrev=""
}

abbreviate_cmd() {
	local limit=40 #-- characters
	if [ ${#${1}} -lt $limit ]
		then printf '$ %s' "$1"
		else printf '$ %.*s[...]' $((limit - 5)) "$1"
	fi
}

precmd () {
	set_title "$(userhost), $(print -P %1~)"

	if (($+cmd_start_time)); then check_stat; fi
}
preexec () {
	set_title "$(userhost), {$(abbreviate_cmd "$1")}"
	cmd_start_time=$((`date "+%s + %N / 1.0e9"`))
	cmd_abbrev=$(abbreviate_cmd ${@})
}


alias wget='noglob wget' #-- the usual workaround™ for "no matches found" with URLs
alias curl='noglob curl'
alias youtube-dl='noglob youtube-dl --prefer-free-formats'

source "$HOME/.profile"
