# Lines configured by zsh-newuser-install
HISTSIZE=1000
SAVEHIST=5000
#setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
HISTFILE=~/.zsh_history
setopt appendhistory autocd nomatch notify
unsetopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install

bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
bindkey "\e[3;5~" delete-word
bindkey "^_" describe-key-briefly # C-?

autoload edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' format '-- completing %d --'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' preserve-prefix '//[^/]##/'
zstyle :compinstall filename '/home/ulidtko/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall


local -H TITLE

PROMPT="%F{green}%U%B%n@%m%u%b%f:%F{blue}%B%~%f%b$ "
TITLE="[%n@%m], %1~"

REPORTTIME=5 # output time statistics when command is running longer than 5 sec
stty tostop # stop background jobs trying to write to the terminal

set_title() {
	case $TERM in
	xterm*|rxvt*)
		print -Pn "\e]0;$@\a"
		;;
	*)
		;;
	esac
}

precmd () {
	set_title $TITLE
}
preexec () {
	set_title "[%n@%m], {$1}"
}
