# Lines configured by zsh-newuser-install
HISTSIZE=1000
SAVEHIST=5000
#setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
HISTFILE=~/.zsh_history
setopt appendhistory autocd nomatch notify
unsetopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install

bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
bindkey "\e[3;5~" delete-word
bindkey "^_" describe-key-briefly # C-?

autoload edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' format '-- completing %d --'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' preserve-prefix '//[^/]##/'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.oh-my-zsh-tweaks"
ZSH_THEME=wedisagree
HYPHEN_INSENSITIVE=true
COMPLETION_WAITING_DOTS=true
DISABLE_UNTRACKED_FILES_DIRTY=true
DISABLE_AUTO_TITLE=true
HIST_STAMPS="yyyy-mm-dd"
plugins=(git branch command-not-found docker web-search cabal npm pip)
source $ZSH/oh-my-zsh.sh

local -H TITLE

REPORTTIME=5 # output time statistics when command is running longer than 5 sec

set_title() {
	case $TERM in
	xterm*|rxvt*)
		print -Pn "\e]0;$@\a"
		;;
	*)
		;;
	esac
}

userhost() {
	if [[ -n $SSH_CLIENT ]]
	then res="[%n@%m]"
	else res="%n"
	fi
	echo $res
}

precmd () {
	set_title "$(userhost), %1~"
}
preexec () {
	set_title "$(userhost), {$1}"
}


alias wget='noglob wget' #-- the usual workaround™ for "no matches found" with URLs
alias youtube-dl='noglob youtube-dl --prefer-free-formats --max-quality 22'

source "$HOME/.profile"
