set nocp " !!!

set showcmd

set shortmess=aI " skip :intro & abbreviate file-messages

set hlsearch incsearch
set ignorecase smartcase " case-insensitive search when pattern all lowercase

set autoindent copyindent preserveindent
set tabstop=8 shiftwidth=4 expandtab smarttab
set softtabstop=0 " what a horrible misfeature
set wrapmargin=120 textwidth=120

set encoding=utf-8
set list listchars=tab:⇥\ ,trail:░

set history=500 " default 20
set undolevels=2000 " default 1000

set title " set cool terminal titles

set nobackup " use scm, dude
set noswapfile " load all into memory; worksforme

set viminfo+=n~/.vim/viminfo

set hidden " hide buffers instead of closing

" when completing in cmdline, ignore some extensions
set wildignore+=*.o,*.hi
" ... and give less priority to files without suffix - probably binary
" executables - over the sources with whatever suffix
set suffixes+=,

set splitright splitbelow

" menu - show popup menu with possible completions
" menuone - show menu even if single completion available
" preview - show preview window with additional information
" longest - complete the longest common prefix of matches
set completeopt=menu,preview,longest


" -=====================- "
" === Plugins section === "
" -=====================- "

" Neovim stuff
if has('nvim')
    set runtimepath^=~/.vim
    let &packpath = &runtimepath
    set shada=!,'100,<50,s10,h,n~/.config/nvim/shada
endif

" Avoid fish surprises for plugins
if &shell =~# 'fish$'
    set shell=sh
endif

" Load everything under vim/bundle/
execute pathogen#infect("bundle/{}")
" Index help files
silent! helptags ALL

" classic
syntax on
filetype plugin indent on

" ---------------------------------------------------------- "
" Per-language defaults kept under ~/.vim/ftplugin/$LANG.vim "
" ---------------------------------------------------------- "

call gina#custom#mapping#nmap(
    \ 'status', 'C', ':<C-u>Gina commit<CR>',
    \ { 'nnoremap': 1, 'silent': 1},
    \)
call gina#custom#mapping#nmap(
    \ 'commit', 'C', ':<C-u>Gina status<CR>',
    \ { 'nnoremap': 1, 'silent': 1},
    \)

" TODO tmux-style ^W-mappings

" -===============================================- "
" === Completions, linters, plugins... settings === "
" -===============================================- "

" ALE
let g:ale_command_wrapper = 'nice -n5'
let g:ale_completion_enabled = 1
set omnifunc=ale#completion#OmniFunc

let g:ale_sign_error = "⚬"
let g:ale_sign_warning = "⚠"
let g:ale_sign_info = "i"
let g:ale_sign_style_error = "!"
let g:ale_sign_style_warning = "🗉"

" YouCompleteMe
let g:ycm_always_populate_location_list = 1
let g:ycm_add_preview_to_completeopt = 1
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_global_ycm_extra_conf = "~/.vim/ycm-global-cflags.py"
"let g:ycm_key_invoke_completion = '<C-Space>' " -- default

au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif

" LSP client
let g:LanguageClient_settingsPath = ['.vim/settings.json', '.vim/lsp-settings.json']
let g:LanguageClient_rootMarkers = ['.git', 'LICENSE', 'COPYING']
let g:LanguageClient_serverCommands = {
  \ 'haskell': ['haskell-language-server-wrapper', '--lsp'],
  \ 'rust': ['rls'],
  \ 'yaml': ['yaml-language-server', '--stdio']
  \ }
let g:LanguageClient_waitOutputTimeout = 3 " seconds, default 10
let g:LanguageClient_useVirtualText = "CodeLens"
let g:LanguageClient_preferredMarkupKind = ['plaintext', 'markdown']
let g:LanguageClient_hoverPreview = "Always"
let g:LanguageClient_trace = "verbose"
let g:LanguageClient_windowLogMessageLevel = "Log"
"let g:LanguageClient_loggingLevel = "DEBUG"
"let g:LanguageClient_loggingFile = "/tmp/vim-lsp-client.log"
"let g:LanguageClient_serverStderr = "/tmp/vim-lsp-server.log"

" :TOhtml settings
let html_use_css = 1
let html_dynamic_folds = 1

" autoloading & autosaving sessions, woooo!
let g:workspace_session_name = '.session.vim'
let g:workspace_session_disable_on_args = 1
if has('nvim')
    au DirChanged * ++nested
        \ if empty(v:this_session) && filereadable(g:workspace_session_name) |
        \   exe ':source ' . g:workspace_session_name |
        \ endif
endif

set wildignore+=__pycache__
set wildignore+=*.egg-info
let g:NERDTreeRespectWildIgnore = 1

let g:ctrlp_max_files = 80000
let g:ctrlp_lazy_update = 180 " typing timeout, ms

" Alternate files
" Needs alt: https://github.com/uptech/alt
" Run a given vim command on the results of alt from a given path.
function! AltCommand(path, vim_command)
  let l:alternate = system("alt " . a:path)
  if empty(l:alternate)
    echo "No alternate file for " . a:path . " found"
  else
    exec a:vim_command . " " . l:alternate
  endif
endfunction

" -=================- "
" === Keybindings === "
" -=================- "

" Reminder: to paste from the OS clipboards, use the + and * special registers:
" [insert] <C-r>+ | [normal] "+p -- pastes the Ctrl-V buffer
" [insert] <C-r>* | [normal] "*p -- pastes the middle-click buffer

    nmap <F2> :NERDTreeToggle<CR>
nnoremap <F4> :call AltCommand(expand('%'), ':e')<CR>
    nmap <F5> :Gina status<CR>
    nmap <F8> :ALEFix<CR>
    nmap <F9> :up<CR>:make<CR>
    nmap <F12> :let &background = (&background == "light") ? "dark" : "light"<CR>
nnoremap <C-f> :CtrlPag<CR>
vnoremap <C-f> :CtrlPagVisual<CR>
nnoremap <C-t> :CtrlPLastMode<CR>
nnoremap <C-p> :CtrlPMixed<CR>

nnoremap <leader>f :CtrlPagLocate
nnoremap <leader>n :CtrlPagPrevious<CR>
nnoremap <leader>d :ALEDetail<CR>

" http://ycm-core.github.io/YouCompleteMe/#ycmcompleter-subcommands
nmap <leader>yg :YcmCompleter GoTo<CR>
nmap <leader>yt :YcmCompleter GetType<CR>
nmap <leader>yr :YcmCompleter RestartServer<CR>
nmap <leader>yd :YcmCompleter GetDocImprecise<CR>

nmap <leader>n :lnext<CR>

nnoremap <F6> :call LanguageClient_contextMenu()<CR>
map <Leader>k :call LanguageClient#textDocument_hover()<CR>
map <Leader>g :call LanguageClient#textDocument_definition()<CR>
map <Leader>r :call LanguageClient#textDocument_rename()<CR>
map <Leader>f :call LanguageClient#textDocument_formatting()<CR>
map <Leader>b :call LanguageClient#textDocument_references()<CR>
map <Leader>a :call LanguageClient#textDocument_codeAction()<CR>
map <Leader>s :call LanguageClient#textDocument_documentSymbol()<CR>
nmap <leader>r :exe (b:LanguageClient_isServerRunning) ? ":LanguageClientStop" : ":LanguageClientStart" <CR>

inoremap <C-space> <C-X><C-o>

" a Clear-All approximation
" TODO join into sensible's Ctrl-L
nnoremap <silent> <Space> :nohlsearch<Bar>:lclose<CR>:cclose<CR>:echo<CR>


" -============- "
" === Colors === "
" -============- "

set termguicolors
"colorscheme darkspectrum
"colorscheme solarized
"colorscheme base16-brewer
"colorscheme base16-chalk
"colorscheme base16-gruvbox-dark-pale
colorscheme base16-material

" Thanks for reading! ^__^
"
" Maybe hit a star on github.com/ulidtko/versioned-configs ;)
"
"                       8888  8888888
"                  888888888888888888888888
"               8888:::8888888888888888888888888
"             8888::::::8888888888888888888888888888
"            88::::::::888:::8888888888888888888888888
"          88888888::::8:::::::::::88888888888888888888
"        888 8::888888::::::::::::::::::88888888888   888
"           88::::88888888::::m::::::::::88888888888    8
"         888888888888888888:M:::::::::::8888888888888
"        88888888888888888888::::::::::::M88888888888888
"        8888888888888888888888:::::::::M8888888888888888
"         8888888888888888888888:::::::M888888888888888888
"        8888888888888888::88888::::::M88888888888888888888
"      88888888888888888:::88888:::::M888888888888888   8888
"     88888888888888888:::88888::::M::;o*M*o;888888888    88
"    88888888888888888:::8888:::::M:::::::::::88888888    8
"   88888888888888888::::88::::::M:;:::::::::::888888888
"  8888888888888888888:::8::::::M::aAa::::::::M8888888888       8
"  88   8888888888::88::::8::::M:::::::::::::888888888888888 8888
" 88  88888888888:::8:::::::::M::::::::::;::88:88888888888888888
" 8  8888888888888:::::::::::M::"@@@@@@@"::::8w8888888888888888
"  88888888888:888::::::::::M:::::"@a@":::::M8i888888888888888
" 8888888888::::88:::::::::M88:::::::::::::M88z88888888888888888
"8888888888:::::8:::::::::M88888:::::::::MM888!888888888888888888
"888888888:::::8:::::::::M8888888MAmmmAMVMM888*88888888   88888888
"888888 M:::::::::::::::M888888888:::::::MM88888888888888   8888888
"8888   M::::::::::::::M88888888888::::::MM888888888888888    88888
" 888   M:::::::::::::M8888888888888M:::::mM888888888888888    8888
"  888  M::::::::::::M8888:888888888888::::m::Mm88888 888888   8888
"   88  M::::::::::::8888:88888888888888888::::::Mm8   88888   888
"   88  M::::::::::8888M::88888::888888888888:::::::Mm88888    88
"   8   MM::::::::8888M:::8888:::::888888888888::::::::Mm8     4
"       8M:::::::8888M:::::888:::::::88:::8888888::::::::Mm    2
"      88MM:::::8888M:::::::88::::::::8:::::888888:::M:::::M
"     8888M:::::888MM::::::::8:::::::::::M::::8888::::M::::M
"    88888M:::::88:M::::::::::8:::::::::::M:::8888::::::M::M
"   88 888MM:::888:M:::::::::::::::::::::::M:8888:::::::::M:
"   8 88888M:::88::M:::::::::::::::::::::::MM:88::::::::::::M
"     88888M:::88::M::::::::::*88*::::::::::M:88::::::::::::::M
"    888888M:::88::M:::::::::88@@88:::::::::M::88::::::::::::::M
"    888888MM::88::MM::::::::88@@88:::::::::M:::8::::::::::::::*8
"    88888  M:::8::MM:::::::::*88*::::::::::M:::::::::::::::::88@@
"    8888   MM::::::MM:::::::::::::::::::::MM:::::::::::::::::88@@
"     888    M:::::::MM:::::::::::::::::::MM::M::::::::::::::::*8
"     888    MM:::::::MMM::::::::::::::::MM:::MM:::::::::::::::M
"      88     M::::::::MMMM:::::::::::MMMM:::::MM::::::::::::MM
"      88    MM:::::::::MMMMMMMMMMMMMMM::::::::MMM::::::::MMM
"        88    MM::::::::::::MMMMMMM::::::::::::::MMMMMMMMMM
"         88   8MM::::::::::::::::::::::::::::::::::MMMMMM
"          8   88MM::::::::::::::::::::::M:::M::::::::MM
"              888MM::::::::::::::::::MM::::::MM::::::MM
"             88888MM:::::::::::::::MMM:::::::mM:::::MM
"             888888MM:::::::::::::MMM:::::::::MMM:::M
"            88888888MM:::::::::::MMM:::::::::::MM:::M
"           88 8888888M:::::::::MMM::::::::::::::M:::M
"           8  888888 M:::::::MM:::::::::::::::::M:::M:
"              888888 M::::::M:::::::::::::::::::M:::MM
"             888888  M:::::M::::::::::::::::::::::::M:M
"             888888  M:::::M:::::::::@::::::::::::::M::M
"             88888   M::::::::::::::@@:::::::::::::::M::M
"            88888   M::::::::::::::@@@::::::::::::::::M::M
"           88888   M:::::::::::::::@@::::::::::::::::::M::M
"          88888   M:::::m::::::::::@::::::::::Mm:::::::M:::M
"          8888   M:::::M:::::::::::::::::::::::MM:::::::M:::M
"         8888   M:::::M:::::::::::::::::::::::MMM::::::::M:::M
"        888    M:::::M:::::::::::::::::::::::MMM:::::::::M::::M
"      8888    MM::::Mm:::::::::::::::::::::MMMM:::::::::m::m:::M
"    888      M:::::M::::::::::::::::::::MMM::::::::::::M::mm:::M
"  8888       MM:::::::::::::::::::::::::MM:::::::::::::mM::MM:::M:
"             M:::::::::::::::::::::::::M:::::::::::::::mM::MM:::Mm
"            MM::::::m:::::::::::::::::::::::::::::::::::M::MM:::MM
"            M::::::::M:::::::::::::::::::::::::::::::::::M::M:::MM
"           MM:::::::::M:::::::::::::M:::::::::::::::::::::M:M:::MM
"           M:::::::::::M88:::::::::M:::::::::::::::::::::::MM::MMM
"           M::::::::::::8888888888M::::::::::::::::::::::::MM::MM
"           M:::::::::::::88888888M:::::::::::::::::::::::::M::MM
"           M::::::::::::::888888M:::::::::::::::::::::::::M::MM
"           M:::::::::::::::88888M:::::::::::::::::::::::::M:MM
"           M:::::::::::::::::88M::::::::::::::::::::::::::MMM
"           M:::::::::::::::::::M::::::::::::::::::::::::::MMM
"           MM:::::::::::::::::M::::::::::::::::::::::::::MMM
"            M:::::::::::::::::M::::::::::::::::::::::::::MMM
"            MM:::::::::::::::M::::::::::::::::::::::::::MMM
"             M:::::::::::::::M:::::::::::::::::::::::::MMM
"             MM:::::::::::::M:::::::::::::::::::::::::MMM
"              M:::::::::::::M::::::::::::::::::::::::MMM
"              MM:::::::::::M::::::::::::::::::::::::MMM
"               M:::::::::::M:::::::::::::::::::::::MMM
"               MM:::::::::M:::::::::::::::::::::::MMM
"                M:::::::::M::::::::::::::::::::::MMM
"                MM:::::::M::::::::::::::::::::::MMM
"                 MM::::::M:::::::::::::::::::::MMM
"                 MM:::::M:::::::::::::::::::::MMM
"                  MM::::M::::::::::::::::::::MMM
"                  MM:::M::::::::::::::::::::MMM
"                   MM::M:::::::::::::::::::MMM
"                   MM:M:::::::::::::::::::MMM
"                   MMM::::::::::::::::::MMM
"                    MM::::::::::::::::::MMM
"                     M:::::::::::::::::MMM
"                    MM::::::::::::::::MMM
"                    MM:::::::::::::::MMM
"                    MM::::M:::::::::MMM:
"                    mMM::::MM:::::::MMMM
"                     MMM:::::::::::MMM:M
"                     mMM:::M:::::::M:M:M
"                      MM::MMMM:::::::M:M
"                      MM::MMM::::::::M:M
"                      mMM::MM::::::::M:M
"                       MM::MM:::::::::M:M
"                       MM::MM::::::::::M:m
"                       MM:::M:::::::::::MM
"                       MMM:::::::::::::::M:
"                       MMM:::::::::::::::M:
"                       MMM::::::::::::::::M
"                       MMM::::::::::::::::M
"                       MMM::::::::::::::::Mm
"                        MM::::::::::::::::MM
"                        MMM:::::::::::::::MM
"                        MMM:::::::::::::::MM
"                        MMM:::::::::::::::MM
"                        MMM:::::::::::::::MM
"                         MM::::::::::::::MMM
"                         MMM:::::::::::::MM
"                         MMM:::::::::::::MM
"                         MMM::::::::::::MM
"                          MM::::::::::::MM
"                          MM::::::::::::MM
"                          MM:::::::::::MM
"                          MMM::::::::::MM
"                          MMM::::::::::MM
"                           MM:::::::::MM
"                           MMM::::::::MM
"                           MMM::::::::MM
"                            MM::::::::MM
"                            MMM::::::MM
"                            MMM::::::MM
"                             MM::::::MM
"                             MM::::::MM
"                              MM:::::MM
"                              MM:::::MM:
"                              MM:::::M:M
"                              MM:::::M:M
"                              :M::::::M:
"                             M:M:::::::M
"                            M:::M::::::M
"                           M::::M::::::M
"                          M:::::M:::::::M
"                         M::::::MM:::::::M
"                         M:::::::M::::::::M
"                         M;:;::::M:::::::::M
"                         M:m:;:::M::::::::::M
"                         MM:m:m::M::::::::;:M
"                          MM:m::MM:::::::;:;M
"                           MM::MMM::::::;:m:M
"                            MMMM MM::::m:m:MM
"                                  MM::::m:MM
"                                   MM::::MM
"                                    MM::MM
"                                     MMMM
