#!/bin/sh
# If a pre-written message is staged in COMMIT_PREPMSG, load it into the
# editor buffer. Only runs on bare `git commit` (not merge/squash/amend).
PREPMSG="$(git rev-parse --git-dir)/COMMIT_PREPMSG"
if [ -z "$2" ] && [ -s "$PREPMSG" ]; then
    mv "$PREPMSG" "$1"
fi
